/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.fineract.los.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.apache.fineract.los.domain.enums.LoanApplicationStatus;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * Root aggregate of the Loan Origination System.
 *
 * <p>Represents a loan application from initial submission through to disbursement. All lifecycle
 * transitions are enforced exclusively by {@code LoanOriginationStateMachine} — no external code
 * may call {@code setStatus} directly.
 *
 * <p>Multi-tenancy: every query must filter by {@code tenantId}. The value is extracted from the
 * {@code X-Fineract-Platform-TenantId} request header.
 *
 * <p>Concurrency: {@code version} provides optimistic locking. Concurrent modification of the same
 * application by two officers will result in an {@code OptimisticLockException} on the second
 * writer — preventing silent data corruption.
 */
@Entity
@Table(name = "loan_application")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
public class LoanApplication {

  /**
   * Internal surrogate primary key. Never exposed in API responses — use {@code applicationRef}.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id", nullable = false, updatable = false)
  private Long id;

  /**
   * Human-readable application reference exposed to clients. Format: LOS-{YEAR}-{SEQUENCE} e.g.
   * LOS-2026-00101. Generated by the service layer on submission.
   */
  @Column(name = "application_ref", nullable = false, unique = true, length = 50, updatable = false)
  private String applicationRef;

  /**
   * Current lifecycle state of this application. Transitions enforced by {@code
   * LoanOriginationStateMachine}. Stored as a string to survive enum additions without migration.
   */
  @Enumerated(EnumType.STRING)
  @Column(name = "status", nullable = false, length = 30)
  private LoanApplicationStatus status;

  /**
   * Amount requested by the applicant. Precision 19, scale 2 — matches Fineract's monetary
   * convention.
   */
  @Column(name = "requested_amount", nullable = false, precision = 19, scale = 2)
  private BigDecimal requestedAmount;

  /**
   * ISO 4217 currency code e.g. USD, INR, KES. Defaults to USD — institutions configure their own
   * default via application.properties.
   */
  @Column(name = "currency", nullable = false, length = 10)
  private String currency = "USD";

  /**
   * Purpose of the loan e.g. AGRICULTURE, EDUCATION, BUSINESS. Used as one factor in credit scoring
   * (10% weight).
   */
  @Column(name = "loan_purpose", length = 100)
  private String loanPurpose;

  /**
   * Requested repayment period in months. Used by the disbursement bridge when constructing the
   * Fineract POST /loans payload.
   */
  @Column(name = "tenor_months")
  private Integer tenorMonths;

  /**
   * Fineract loan product identifier this application will be disbursed against. Populated at
   * application creation time (institution configures a default product per loan purpose, or the
   * caller supplies it explicitly). Required before the disbursement bridge can run.
   */
  @Column(name = "fineract_loan_product_id")
  private Long fineractLoanProductId;

  /**
   * The Fineract {@code loanId} returned by {@code POST /loans} once the disbursement bridge has
   * successfully created the loan. Null until the application reaches DISBURSED. Immutable once set
   * — this is the audit link between the external LOS record and the Fineract core loan.
   */
  @Column(name = "fineract_loan_id")
  private Long fineractLoanId;

  /**
   * Tenant identifier — maps to the institution using this LOS. Extracted from
   * X-Fineract-Platform-TenantId header. Every repository query MUST filter by this field.
   */
  @Column(name = "tenant_id", nullable = false, length = 100, updatable = false)
  private String tenantId;

  /**
   * Optimistic locking version counter. Automatically incremented by JPA on every update. Prevents
   * concurrent modification corruption when two officers act on the same application
   * simultaneously.
   */
  @Version
  @Column(name = "version")
  private Long version;

  /**
   * Timestamp of initial creation. Set automatically by Spring Data Auditing. Never updated after
   * creation.
   */
  @CreatedDate
  @Column(name = "created_at", nullable = false, updatable = false)
  private LocalDateTime createdAt;

  /**
   * Timestamp of last modification. Updated automatically by Spring Data Auditing on every save
   * operation.
   */
  @LastModifiedDate
  @Column(name = "updated_at", nullable = false)
  private LocalDateTime updatedAt;
}
